### ISSUE TITLE
Update Bamboo

### ISSUE THREAD

**Issue by TWME-TW** [MenschenToaster/CraftFlowers#17]
Because

![image](https://user-images.githubusercontent.com/65117253/180386719-a0db6830-2d9a-414c-a4f0-1c0736dac03f.png)

**Comment by TWME-TW** [comment]
I can't figure out how to do it

**Comment by TWME-TW** [comment]
Maybe add age and leaves options

and add bamboo_sapling(It doesn't seem to exist at the moment?)

**Comment by MenschenToaster** [comment]
You could theoretically add options for each age+leaves+stage combo. But that will end up in a lot of items. We will probably need to implement a bamboo builder with different GUIs that open after each other (or everything in one gui) for selecting age, leave type and stage. 

It can be implemented by creating a BambooFlower class that extends AgingFlower and implements the various options(leave type and stage). And then manually implementing a GUI and checking for it in BlockPlaceListener.

You can try to do it but if you think its too complicated I can look at it when I have some time to look into this.
If you are implementing a GUI, please use the GUI library we used for the other GUIs.

**Comment by TWME-TW** [comment]
> You could theoretically add options for each age+leaves+stage combo. But that will end up in a lot of items. We will probably need to implement a bamboo builder with different GUIs that open after each other (or everything in one gui) for selecting age, leave type and stage.
> 
> It can be implemented by creating a BambooFlower class that extends AgingFlower and implements the various options(leave type and stage). And then manually implementing a GUI and checking for it in BlockPlaceListener.
> 
> You can try to do it but if you think its too complicated I can look at it when I have some time to look into this. If you are implementing a GUI, please use the GUI library we used for the other GUIs.

It's too difficult for me, so I won't write this.
