### ISSUE TITLE
Seems to be broken in 1.16.4.

### ISSUE THREAD

**Issue by JustJP2K** [MenschenToaster/CraftFlowers#2]
I am using 1.16.4 and newest FAWE worldedit. however i cannot place any of the custom flowers even with all permissions. i am using towny. but i also have the permission fawe.towny. 

Any help?

**Comment by MenschenToaster** [comment]
Is it working for you wighout Twony? Try starting a Server with the Same Start Jar and only use FAWE and Craftflowers.

Additionally:
What Fawe and what Spigot/Paper Version are you using?

**Comment by MenschenToaster** [comment]
Sorry for the late Reply. I wasnt really looking into my Github Messages ;)

**Comment by JustJP2K** [comment]
ill try it out in a bit. also craftflowers seems to start up using the main thread and straining the server quite a bit

**Comment by JustJP2K** [comment]
so i had to remove it since it was almost impossible to log in

**Comment by MenschenToaster** [comment]
I see where the Thread is being blocked. I will fix this later. @Tombonation is currently also working on an update, so I will wait for that and then update. ^^

**Comment by JustJP2K** [comment]
alright :) ill wait for the update and see if that fixes the issue ive been having. if not ill get back to this issue :P

**Comment by MenschenToaster** [comment]
New Version is out now. It will probably take Spigot a while before it shows in game but there you go ;)

**Comment by MenschenToaster** [comment]
There is 0.7.1 now. It improves the Performance even more ;)

**Comment by JustJP2K** [comment]
ok it seems to have fixed it :P
