### ISSUE TITLE
Only be able to craft with items in inventory

### ISSUE THREAD

**Issue by JustJP2K** [MenschenToaster/CraftFlowers#3]
It would be a nice addition that you could only craft the flowers with the flower items you have in your inventory if you are not in creative mode and then get taken away once its crafted. otherwise you could just dupe the flowers over and over and get infinite flowers :P 

Also the flower pot should be a one time use if you arent in creative.

**Comment by MenschenToaster** [comment]
The Plugin was afaik never made to run on Survival Servers. It's a Create Building Plugin and will probably be forever.
Maybe I will add this in the Future. You can leave the issue open, and maybe I will add it sometime.

**Comment by MenschenToaster** [comment]
No Problem. I pinned it, so it won't get lost ;)

**Comment by JustJP2K** [comment]
ye thx :3

**Comment by MenschenToaster** [comment]
Took a Year, but now It's finally here. Public release will follow in the next days ^^
