### ISSUE TITLE
Suggestion: Add list of plants under item

### ISSUE THREAD

**Issue by NoltoxGit** [MenschenToaster/CraftFlowers#34]
Hello!

My players suggested me to add the list of selected plants in the CraftFlowers menu, for example :
![image](https://user-images.githubusercontent.com/75265787/227715147-08af7c4d-e831-4490-8d5a-601d70c6494d.png)

Looking forward to your feedback on this :)
~ Noltox ~

**Comment by MenschenToaster** [comment]
I will add it in the future. Although, development on this project is quite slow, so it will take a while. 

If anybody wants to do a PR, I'm more than happy to review and merge it.
