### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by NoltoxGit** [MenschenToaster/CraftFlowers#9]
Hello @MenschenToaster,
The plugin is great for Creative servers, but with one exception, would it be possible to translate more things than just the prefix and arrows, such as the name of the menu, the items inside and the commands?

**Thanks for the plugin anyway!**

**Comment by MenschenToaster** [comment]
Hey @NoltoxGit,

I will try to add translatable messages when I have more time for the plugin.

The Item translation part could be a bit harder considering how the plugin works right now. But I will look into it :)

**Comment by NoltoxGit** [comment]
> Hey @NoltoxGit,
> 
> I will try to add translatable messages when I have more time for the plugin.
> 
> The Item translation part could be a bit harder considering how the plugin works right now. But I will look into it :)

Thanks for your reply, and I can't wait to see it :)

**Comment by NoltoxGit** [comment]
oops sorry x)

**Comment by NoltoxGit** [comment]
Hello @MenschenToaster 
I hope you are well :)

Would it be possible to have some news on my suggestion?

~ Noltox ~

**Comment by NoltoxGit** [comment]
Hello @MenschenToaster 
I hope you are well :)

Would it be possible to have some news on my suggestion?

~ Noltox ~

**Comment by MenschenToaster** [comment]
See Pull Request #19. Should be there in the next release

**Comment by NoltoxGit** [comment]
Oh, excellent!
Thanks a lot :)

Looking forward to the update!
